### ISSUE TITLE
Waiting for the great code

### ISSUE THREAD

**Issue by howardgriffin** [YBYBZhang/VideoElevator#1]

**Comment by YBYBZhang** [comment]
Thanks for your appreciation! We're refactoring and cleaning the code currently, and will release it in end of March or early April.

**Comment by devin12422** [comment]
Are you guys going to release any pretrained weights?

**Comment by Ednaordinary** [comment]
> Are you guys going to release any pretrained weights?
>

VideoElevator just combines (leverages) a T2I to a T2V model right? So there aren't any weights to release, only code (unless compute cost of combination is significantly higher than the cost of generation, then they should release some sample weights. I'm guessing it's on demand or straight up separate though)

Correct me if that's wrong
