### ISSUE TITLE
What other implementation methods can be provided in the video？

### ISSUE THREAD

**Issue by zhanghongyong123456** [YBYBZhang/VideoElevator#2]
I found that several implementation methods (LaVie + realisticVision；AnimateDiff XL + DynaVision；Animate DIff + SDv2.1-base ) in the demonstration video are very effective, can you give the corresponding implementation process，Extremely stable and HD
![01](https://github.com/YBYBZhang/VideoElevator/assets/48466610/b1f66685-622e-4ded-be2d-23dd78700753)
![02](https://github.com/YBYBZhang/VideoElevator/assets/48466610/74672289-eef0-48dd-9dcc-cfe1996e8957)
![03](https://github.com/YBYBZhang/VideoElevator/assets/48466610/3c97d5ed-9315-4d67-b567-e88aec5410fd)

for  LaVie   only  use   stable-diffusion-v1-4  model run  ,how   chage    base   model realisticVision?

**Comment by YBYBZhang** [comment]
Thanks for your great attention and appreciation! Our VideoElevator leverages powerful text-to-image diffusion models (T2I) to enhance the performance of text-to-video diffusion models (T2V), as long as T2I and T2V have the same autoencoder.
For example, LaVie inherits the autoencoder from SDv1.4 while RealisticVision inherits it from SDv1.5, where SDv1.4 and SDv1.5 have the same autoencoder. Therefore, LaVie can be effectively enhanced with RealisticVision.

We're refactoring and cleaning the code recently, and will release it in end of March or early of April !

**Comment by johndpope** [comment]
run the code through claude / chatgpt to clean up. you can give it the paper to have it comment the code along side.
I built this repo doing that - https://github.com/johndpope/emote-hack
