### ISSUE TITLE
what hyperparameter does "stable_num" represent in the paper?

### ISSUE THREAD

**Issue by Tonniia** [YBYBZhang/VideoElevator#4]
Hi. I am interested in this T2V T2I composing work. I have some questions: 
1. Could you please clarify what the term "stable_num" in the code refers to in the context of the paper? I've been unable to locate any relevant information about this hyperparameter in the paper. 
2. In the paper, it seems that for each denoising step, there is one T2V and one T2I. In the code, it seems that there is only a few stable steps.
Your guidance would be greatly appreciated. Thank you!

**Comment by YBYBZhang** [comment]
Sorry for the late reply.
1. "stable_num" refers to N in Fig.3 of paper, which means the number of T2V steps at each sampling step.
2. In the code, T2V and T2I are "self.unet3d" and "self.unet", respectively. https://github.com/YBYBZhang/VideoElevator/blob/557d77c30416569f4c377cb6f62aa092bedb8cd9/pipelines/videoelevator_pipeline.py#L241
https://github.com/YBYBZhang/VideoElevator/blob/557d77c30416569f4c377cb6f62aa092bedb8cd9/pipelines/videoelevator_pipeline.py#L242
